module.exports = {
	baseUrl: 'https://raw.githubusercontent.com/abecms/abecms/4.x-alpha/docs/',
	extension: 'md',
	listOfFiles: [
		'abe-attributes',
		'abe-config',
		'abe-dev-type',
		'abe-document',
		'abe-form-create-override',
		'abe-engine-override',
		'abe-generate-posts',
		'abe-handlebars-helpers',
		'abe-handlebars-variables',
		'abe-hooks',
		'abe-linux-commands',
		'abe-locale',
		'abe-logs',
		'abe-plugins',
		'abe-process',
		'abe-smtp',
		'abe-ssl',
		'abe-tags',
		'abe-update-json',
		'abe-url',
		'abe-users',
		'types/abe-data',
		'types/abe-each',
		'types/abe-file',
		'types/abe-image',
		'types/abe-import',
		'types/abe-link',
		'types/abe-rich',
		'types/abe-slug',
		'types/abe-sql',
		'types/abe-template',
		'types/abe-textarea',
		'types/abe-translate',
		'handlebars-helpers/isAuthorized'
	]
}